#!/usr/bin/env python3
"""Create deterministic wheels from hash-verified installed distributions.

An immutable container can contain a qualified package after its source wheel
was created and removed in one image layer. Docker cannot recover such a wheel
from layer history. This tool verifies every hashed installed file recorded by
the distribution, excludes installation-generated metadata and bytecode, and
packs the remaining qualified payload into a distributable wheel.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import importlib.metadata
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath


INSTALLATION_METADATA = {"INSTALLER", "RECORD", "REQUESTED", "direct_url.json"}
TORCH_LIBRARY_RUNPATH = ":".join(
    (
        "$ORIGIN",
        "$ORIGIN/../../nvidia/cu13/lib",
        "$ORIGIN/../../nvidia/cudnn/lib",
        "$ORIGIN/../../nvidia/nvshmem/lib",
        "$ORIGIN/../../local_inference_nccl/lib",
    )
)


def parse_allowed_modification(value: str) -> tuple[PurePosixPath, str]:
    """Parse an installed-file digest that intentionally differs from RECORD."""
    try:
        path_text, digest = value.rsplit("=", 1)
    except ValueError as error:
        raise argparse.ArgumentTypeError(
            "allowed modification must have the form WHEEL_PATH=SHA256"
        ) from error
    path = PurePosixPath(path_text)
    if path.is_absolute() or ".." in path.parts or not path.name:
        raise argparse.ArgumentTypeError(f"invalid wheel path: {path_text!r}")
    if len(digest) != 64 or any(char not in "0123456789abcdef" for char in digest):
        raise argparse.ArgumentTypeError(f"invalid SHA-256 digest: {digest!r}")
    return path, digest


def sha256(path: Path) -> str:
    """Return the hexadecimal SHA-256 digest of one file."""
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(8 * 1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def record_digest(path: Path) -> str:
    """Return the URL-safe base64 SHA-256 value used in wheel RECORD files."""
    raw = bytes.fromhex(sha256(path))
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def is_installation_generated(path: PurePosixPath) -> bool:
    """Return whether a RECORD entry was generated by wheel installation."""
    return (
        ".." in path.parts
        or "__pycache__" in path.parts
        or path.suffix == ".pyc"
        or (".dist-info" in path.parent.name and path.name in INSTALLATION_METADATA)
    )


def normalize_tree_mtime(root: Path, epoch: int) -> None:
    """Set a stable timestamp on every staged directory and regular file."""
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_symlink():
            continue
        os.utime(path, (epoch, epoch))
    os.utime(root, (epoch, epoch))


def rewrite_torch_library_runpaths(stage: Path) -> list[dict[str, str]]:
    """Make staged Torch libraries resolve CUDA and NCCL inside the venv."""
    library_dir = stage / "torch" / "lib"
    rewritten: list[dict[str, str]] = []
    for path in sorted(library_dir.iterdir()):
        if not path.is_file():
            continue
        result = subprocess.run(
            ["patchelf", "--print-rpath", str(path)],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0 or not result.stdout.strip():
            continue
        original = result.stdout.strip()
        subprocess.run(
            ["patchelf", "--set-rpath", TORCH_LIBRARY_RUNPATH, str(path)],
            check=True,
        )
        rewritten.append(
            {
                "path": str(path.relative_to(stage)),
                "original_runpath": original,
                "packaged_runpath": TORCH_LIBRARY_RUNPATH,
                "packaged_sha256": sha256(path),
            }
        )
    if not rewritten:
        raise RuntimeError("Torch distribution contained no libraries with a runpath")
    return rewritten


def repack_distribution(
    name: str,
    output_dir: Path,
    epoch: int,
    allowed_modifications: dict[PurePosixPath, str] | None = None,
    rewrite_torch_runpaths: bool = False,
) -> dict[str, object]:
    """Verify and repack one installed distribution into ``output_dir``."""
    distribution = importlib.metadata.distribution(name)
    files = distribution.files
    if files is None:
        raise RuntimeError(f"distribution has no RECORD file list: {name}")
    source_record = Path(distribution._path) / "RECORD"
    if not source_record.is_file():
        raise RuntimeError(f"distribution RECORD is absent: {name}")

    allowed_modifications = allowed_modifications or {}
    copied: list[str] = []
    skipped: list[str] = []
    verified_modifications: list[dict[str, str]] = []
    with tempfile.TemporaryDirectory(prefix=f"repack-{name}-") as temporary:
        stage = Path(temporary) / "payload"
        stage.mkdir()
        for package_path in files:
            relative = PurePosixPath(str(package_path))
            source = Path(distribution.locate_file(package_path))
            if not source.is_file():
                raise RuntimeError(f"installed RECORD path is absent: {relative}")
            if package_path.hash is not None:
                installed_digest = sha256(source)
                record_value = package_path.hash.value
                if package_path.hash.mode != "sha256":
                    raise RuntimeError(f"unsupported RECORD digest mode: {relative}")
                if record_digest(source) != record_value:
                    declared_digest = allowed_modifications.get(relative)
                    if installed_digest != declared_digest:
                        raise RuntimeError(
                            f"installed RECORD digest mismatch: {relative}"
                        )
                    verified_modifications.append(
                        {
                            "path": str(relative),
                            "record_sha256": base64.urlsafe_b64decode(
                                record_value + "=" * (-len(record_value) % 4)
                            ).hex(),
                            "installed_sha256": installed_digest,
                        }
                    )
            if is_installation_generated(relative):
                skipped.append(str(relative))
                continue
            destination = stage.joinpath(*relative.parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, destination)
            shutil.copymode(source, destination)
            copied.append(str(relative))

        runpath_rewrites = (
            rewrite_torch_library_runpaths(stage) if rewrite_torch_runpaths else []
        )
        normalize_tree_mtime(stage, epoch)
        before = set(output_dir.glob("*.whl"))
        environment = os.environ.copy()
        environment["SOURCE_DATE_EPOCH"] = str(epoch)
        subprocess.run(
            [
                sys.executable,
                "-m",
                "wheel",
                "pack",
                "--dest-dir",
                str(output_dir),
                str(stage),
            ],
            check=True,
            env=environment,
            stdout=sys.stderr,
        )
        produced = set(output_dir.glob("*.whl")) - before
        if len(produced) != 1:
            raise RuntimeError(f"wheel pack produced {len(produced)} files for {name}")
        wheel = produced.pop()

    return {
        "name": distribution.metadata["Name"],
        "version": distribution.version,
        "source_record_sha256": sha256(source_record),
        "copied_file_count": len(copied),
        "skipped_installation_file_count": len(skipped),
        "verified_record_modifications": verified_modifications,
        "runpath_rewrites": runpath_rewrites,
        "wheel": wheel.name,
        "wheel_sha256": sha256(wheel),
    }


def main() -> None:
    """Repack requested packages and write their provenance manifest."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--source-date-epoch", type=int, required=True)
    parser.add_argument(
        "--allow-modified-record-entry",
        action="append",
        default=[],
        type=parse_allowed_modification,
        metavar="WHEEL_PATH=SHA256",
        help=(
            "accept one image-build mutation only when its installed SHA-256 "
            "matches the declared digest"
        ),
    )
    parser.add_argument(
        "--rewrite-torch-runpaths",
        action="store_true",
        help="replace NGC host paths with venv-relative CUDA and NCCL paths",
    )
    parser.add_argument("package", nargs="+")
    args = parser.parse_args()
    allowed_modifications = dict(args.allow_modified_record_entry)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    results = [
        repack_distribution(
            package,
            args.output_dir,
            args.source_date_epoch,
            allowed_modifications,
            rewrite_torch_runpaths=args.rewrite_torch_runpaths and package == "torch",
        )
        for package in args.package
    ]
    verified_paths = {
        PurePosixPath(modification["path"])
        for result in results
        for modification in result["verified_record_modifications"]
    }
    unverified_paths = set(allowed_modifications) - verified_paths
    if unverified_paths:
        missing = ", ".join(str(path) for path in sorted(unverified_paths))
        raise RuntimeError(f"declared RECORD modifications were not observed: {missing}")
    print(
        json.dumps(
            {
                "schema": "local-inference-installed-distribution-repack/v1",
                "status": "implemented",
                "packages": results,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
